apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: spin-paradigma-world
  name: spin-paradigma-world
spec:
  runtimeClassName: wasmtime-spin-v0-8-0
  containers:
  - image: poc.azurecr.io/ydguala/hello-paradigma-world-provenance:latest
    imagePullPolicy: Always
    name: spin-paradigma-world
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spin-paradigma-world-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: spin-paradigma-world
