apiVersion: v1
kind: Service
metadata:
  name: jmx-test
spec:
  selector:
    app: jmx-test
  ports:
  - name: http
    port: 9991
    targetPort: 9991
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmx-test
spec:
  selector:
    matchLabels:
      app: jmx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: jmx-test
    spec:
      containers:
      - name: jmx-test
        image: ydguala/jmxtest:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9991